### ISSUE TITLE
Diagnostics incorrectly detects duplicate injection member

### ISSUE THREAD

**Issue by karelkral** [unitycontainer/container#168]
When using Diagnostics extension, this extension incorrectly fails with the message

`System.InvalidOperationException: 'Method Initialize(Xunit.Sdk.AsyncTestSyncContext) is ambiguous, it could be matched with more than one method on type WpfSyncContextProvider.'`

although the method exists only once in `WpfSyncContextProvider`.

### To Reproduce
Run attached unit tests. The Unit test fails with a message above. See `WpfSyncContextProvider` . This class has only one Initialize method.

```cs
public class WpfSyncContextProvider 
{

	private SynchronizationContext _syncContext;

	public WpfSyncContextProvider()
	{
	}

	public void Initialize(SynchronizationContext syncContext)
	{
		if (!(syncContext is DispatcherSynchronizationContext))
		{
			throw new InvalidOperationException("Error");
		}

		_syncContext = syncContext;
	}

}

public class WpfSyncContextProviderTests
{

	[Fact]
	public void WpfSyncContextProviderCanBeRegistered_WithContainer()
	{
		UnityContainer container = new UnityContainer();
		container.AddExtension(new Diagnostic());
		container.RegisterSingleton<WpfSyncContextProvider>(new InjectionMethod(nameof(WpfSyncContextProvider.Initialize), SynchronizationContext.Current));
	}
}

**Comment by ENikS** [comment]
This does not compile

**Comment by karelkral** [comment]
Simpler code follows. Requires references bellow. 

````
System.InvalidOperationException: Method Initialize() is ambiguous, it could be matched with more than one method on type DummyClass.

  Error in:  RegisterType<DummyClass>(Lifetime:PerContainer, Invoke.Method('Initialize', ))

   at Unity.UnityContainer.Unity.IUnityContainer.RegisterType(Type typeFrom, Type typeTo, String name, ITypeLifetimeManager lifetimeManager, InjectionMember[] injectionMembers)
   at Unity.UnityContainerExtensions.RegisterSingleton[T](IUnityContainer container, InjectionMember[] injectionMembers)
   at UnityWithInjectionMember.DummyClassTests.WpfSyncContextProviderCanBeRegistered_WithContainer() in F:\Repos\CICD\Src\SandBox\UnityWithInjectionMember\DummyClassTests.cs:line 27
System.ArgumentException: Method Initialize() is ambiguous, it could be matched with more than one method on type DummyClass.
   at Unity.Injection.Validating.<>c.<.cctor>b__4_1(Type type, InjectionMember member)
   at Unity.Injection.InjectionMember`2.AddPolicies[TContext,TPolicySet](Type registeredType, Type mappedToType, String name, TPolicySet& policies)
   at Unity.UnityContainer.Unity.IUnityContainer.RegisterType(Type typeFrom, Type typeTo, String name, ITypeLifetimeManager lifetimeManager, InjectionMember[] injectionMembers)
````

````xml
  <ItemGroup>
    <PackageReference Include="Unity">
      <Version>5.10.3</Version>
    </PackageReference>
    <PackageReference Include="xunit">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="xunit.analyzers">
      <Version>0.10.0</Version>
    </PackageReference>
    <PackageReference Include="xunit.runner.console">
      <Version>2.4.1</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
````
````cs
using System;
using System.Linq;
using Unity;
using Unity.Injection;
using Xunit;

namespace UnityWithInjectionMember
{

	public class DummyClass
	{

		public void Initialize()
		{

		}
	}

	public class DummyClassTests
	{

		[Fact]
		public void WpfSyncContextProviderCanBeRegistered_WithContainer()
		{
			UnityContainer container = new UnityContainer();
			container.AddExtension(new Diagnostic());
			container.RegisterSingleton<DummyClass>(new InjectionMethod(nameof(DummyClass.Initialize)));
		}
	}
}

**Comment by karelkral** [comment]
Hello, an example is completed several months, but still no movement.

**Comment by itsho** [comment]
it seems that it **does** matter where we call `Container.AddNewExtension<Diagnostic>();`.

To reproduce this error in **`Configuration.Tests`** project, modify **`ContainerConfiguringFixture`** to look like this:

```
protected override void Arrange()
{
    base.Arrange();
    this.Container = new UnityContainer();
    Container.AddNewExtension<Diagnostic>(); // <-- add this line here.
}
```

Then, **all** of the tests in the class **`When_ConfigurationContainerForMethodInjection`** will raise _InvalidOperationException_.


I would suggest (to the end-users), to add the diagnostics only when all registrations are done - if possible.



![Unity V5-TestsFailWithDiagnostics](https://user-images.githubusercontent.com/1774797/65389517-cea40c80-dd5f-11e9-83c4-ab2dd0ef8532.png)
