### ISSUE TITLE
`AccessViolationException` when enumerating ResolveEnumerable

### ISSUE THREAD

**Issue by Pretasoc** [unitycontainer/container#203]
### Description

In my application i inject a `IEnumerable<T>` into a class. This enumerable will later be processed, possible on an other thread. When trying to enumerate the dependencies. The enumeration fails with an `AccessViolationException`.

I wasn't able, to provide a unit test until now. The project the error occured in, is a closed source, and i failed to recreate an envrionment, in wich the test failed. 

**Additional context**
I hope this stack trace helps to locate the problem.

>    at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|125_0(IntPtr parent, Type registrationType, String name) in C:\projects\container\src\UnityContainer.Resolution.cs:line 506
   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|125_0(IntPtr parent, Type registrationType, String name) in C:\projects\container\src\UnityContainer.Resolution.cs:line 500
   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|125_0(IntPtr parent, Type registrationType, String name) in C:\projects\container\src\UnityContainer.Resolution.cs:line 500
   at Unity.UnityContainer.<ContextValidatingExecutePlan>g__GetPerResolveValue|125_0(IntPtr parent, Type registrationType, String name) in C:\projects\container\src\UnityContainer.Resolution.cs:line 500
   at Unity.UnityContainer.ContextValidatingExecutePlan(BuilderStrategy[] chain, BuilderContext& context) in C:\projects\container\src\UnityContainer.Resolution.cs:line 461
   at Unity.Builder.BuilderContext.Resolve(Type type, String name, InternalRegistration registration) in C:\projects\container\src\Builder\Context\BuilderContext.cs:line 177
   at Unity.UnityContainer.<ResolveEnumerable>d__107`1.MoveNext() in C:\projects\container\src\UnityContainer.Resolution.cs:line 127

**Comment by Pretasoc** [comment]
Maybe the `HandleProcessCorruptedStateExceptionsAttribute` would help, to catch the exception.

**Comment by anlau** [comment]
Is the diagnostic fonctionality enabled (something like `container.EnableDiagnostic()`)? See [issue 306](https://github.com/unitycontainer/unity/issues/306) in unitycontainer/unity.

**Comment by Pretasoc** [comment]
Yes, diagnostic were enabled. Disabling them solved the isussue.
