### ISSUE TITLE
Exception: Value of ContainerControlledLifetimeManager can only be set once

### ISSUE THREAD

**Issue by pksorensen** [unitycontainer/container#70]
Sorry, at this point I have no repo of the case - but i saw the following i my logs.

```
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'SInnovations.ServiceFabric.GatewayService.Actors.GatewayServiceManagerActor', name = '(none)'.\nException occurred while: while resolving.\nException is: InvalidOperationException - Value of ContainerControlledLifetimeManager can only be set once\n-----------------------------------------------\nAt the time of the exception, the container was: 
  Resolving SInnovations.ServiceFabric.GatewayService.Actors.GatewayServiceManagerActor,(none)
  Resolving parameter 'arg5' of constructor SInnovations.ServiceFabric.GatewayService.Actors.GatewayServiceManagerActorProxy(SInnovations.ServiceFabric.Unity.IActorDeactivationInterception arg0, Microsoft.ServiceFabric.Actors.Runtime.ActorService arg1, Microsoft.ServiceFabric.Actors.ActorId arg2, SInnovations.ServiceFabric.Storage.Configuration.StorageConfiguration arg3, SInnovations.ServiceFabric.GatewayService.Configuration.CloudFlareZoneService arg4, SInnovations.LetsEncrypt.LetsEncryptService`1[[Certes.AcmeContext, Certes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] arg5)
    Resolving SInnovations.LetsEncrypt.LetsEncryptService`1[Certes.AcmeContext],(none)
    Resolving parameter 'acmeClientService' of constructor SInnovations.LetsEncrypt.LetsEncryptService`1[[Certes.AcmeContext, Certes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]](SInnovations.LetsEncrypt.LetsEncryptServiceOptions options, SInnovations.LetsEncrypt.Services.IAcmeClientService`1[[Certes.AcmeContext, Certes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] acmeClientService, SInnovations.LetsEncrypt.Services.ILetsEncryptChallengeService`1[[Certes.AcmeContext, Certes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] challengeService, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory)
      Resolving SInnovations.LetsEncrypt.Services.IAcmeClientService`1[Certes.AcmeContext],(none)
      Resolving parameter 'orders' of constructor SInnovations.LetsEncrypt.Services.Defaults.CertesAcmeClientService(SInnovations.LetsEncrypt.Stores.IRS256SignerStore store, SInnovations.LetsEncrypt.Services.Defaults.IOrders orders)
        Resolving SInnovations.LetsEncrypt.Services.Defaults.IOrders,(none)
          Resolving SInnovations.LetsEncrypt.Services.Defaults.CertesChallengeService,(none)
          Resolving parameter 'dnsClient' of constructor SInnovations.LetsEncrypt.Services.Defaults.CertesChallengeService(SInnovations.LetsEncrypt.Clients.IDnsClient dnsClient)
            Resolving SInnovations.LetsEncrypt.Clients.IDnsClient,(none)
            Resolving parameter 'dnsfallback' of constructor SInnovations.ServiceFabric.GatewayService.Configuration.CloudFlareDNSClient(System.Net.Http.HttpClient http, SInnovations.LetsEncrypt.DnsMadeEasyManager.LetsEncryptDnsMadeEasyManager dnsfallback, Microsoft.Extensions.Options.IOptions`1[[SInnovations.ServiceFabric.GatewayService.Configuration.KeyVaultOptions, S-Innovations.ServiceFabric.GatewayService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] secrets, SInnovations.ServiceFabric.GatewayService.Configuration.CloudFlareZoneService cloudFlareZoneService)
              Resolving SInnovations.LetsEncrypt.DnsMadeEasyManager.LetsEncryptDnsMadeEasyManager,(none)
              Resolving parameter 'credentials' of constructor SInnovations.LetsEncrypt.DnsMadeEasyManager.LetsEncryptDnsMadeEasyManager(SInnovations.DnsMadeEasy.DnsMadeEasyClientCredetials credentials)
                Resolving SInnovations.DnsMadeEasy.DnsMadeEasyClientCredetials,(none)
                Resolving parameter 'keyvault' of constructor SInnovations.ServiceFabric.GatewayService.Configuration.DnsMadeEasyOptions(Microsoft.Extensions.Options.IOptions`1[[SInnovations.ServiceFabric.GatewayService.Configuration.KeyVaultOptions, S-Innovations.ServiceFabric.GatewayService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] keyvault)
                  Resolving Microsoft.Extensions.Options.IOptions`1[SInnovations.ServiceFabric.GatewayService.Configuration.KeyVaultOptions],(none)
 ---> System.InvalidOperationException: Value of ContainerControlledLifetimeManager can only be set once
   at Unity.Lifetime.ContainerControlledLifetimeManager.<>c.<SetValue>b__5_0(Object o, ILifetimeContainer c)
   at Unity.Lifetime.ContainerControlledLifetimeManager.SetValue(Object newValue, ILifetimeContainer container)
   at Unity.Strategies.LifetimeStrategy.PostBuildUp(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)\n   at Unity.Builder.BuilderContext.BuildUp()
   at Unity.Strategies.BuildKeyMappingStrategy.<>c__DisplayClass0_0.<PreBuildUp>b__0(IBuilderContext c)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.Builder.BuilderContext.NewBuildUp(Type type, String name, Action`1 childCustomizationBlock)
   at lambda_method(Closure , IBuilderContext )
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
```

And looking at the trace, i am considering that the issue is Thread related at the core of Unity.Container and not in the application code. 

Just wanted to log this for now and try to find more information about the issue.

**Comment by ENikS** [comment]
```
---> System.InvalidOperationException: Value of ContainerControlledLifetimeManager can only be set ...
```
Looks like this manager is being reused somewhere in your code. It can only be set once.

**Comment by pksorensen** [comment]
Ye, i saw that and just wonder how that can happen when only using the public api of unity. 

I dont have any new ContainerControllerLifetimeManagers being shared about registrations.

I will see if i can reproduce it further.

**Comment by pksorensen** [comment]
i managed to reproduce my issue.

```

    public interface ITest1
    {

    }

    public interface ITest2
    {

    }
    public class TestOptions
    {

    }
    public class Test1 : ITest1, ITest2
    {
       
        public Test1(IOptions<TestOptions> options)
        { 

        }

    }

  [TestMethod]
        public void Test3()
        {
            var container = new UnityContainer();
            container.RegisterType<Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest1, Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest2, Test1>(new HierarchicalLifetimeManager());

            container.RegisterType(typeof(IOptions<>), typeof(OptionsManager<>), new ContainerControlledLifetimeManager())
              .RegisterType(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>), new HierarchicalLifetimeManager())
         .RegisterType(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>), new ContainerControlledLifetimeManager())
          .RegisterType(typeof(IOptionsFactory<>), typeof(OptionsFactory<>), new TransientLifetimeManager())
         .RegisterType(typeof(IOptionsMonitorCache<>), typeof(OptionsCache<>), new ContainerControlledLifetimeManager());

            {
                var child = container.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest2>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());

                child.Dispose();
            }
            {
                var child = container.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest2>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());
            }
             
        }

```

In aspnet core the IOptions<> is registered as a singleton

https://github.com/aspnet/Options/blob/37b40ed82e196aa897cd574ef35c3fd6d3d4d9f3/src/Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs#L30

but if i use the Unity.Microsoft.DependencyInjection - it looks like to be working

```
  [TestMethod]
        public void Test4()
        {
            var serviceColection = new ServiceCollection();
            serviceColection.AddOptions();
     
            var container = new UnityContainer();
            container.RegisterType<Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest1, Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest2, Test1>(new HierarchicalLifetimeManager());

            var factory = new ServiceProviderFactory(container);

            var childcontainer = factory.CreateBuilder(serviceColection) ;

            {
                var child = childcontainer.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest1>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());

                child.Dispose();
            }
            {
                var child = childcontainer.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest1>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());
            }

        }
```

## Conclusion

I am using IOptions outside aspnet core and with unity and the issue is therefore related to me doing:

```
container.RegisterType(typeof(IOptions<>), typeof(OptionsManager<>), new ContainerControlledLifetimeManager())
```

Are there any way that I can make this work?
Can i use   InjectionSingletonLifetimeManager ?, how do i do the registration

```
  container.RegisterType(typeof(IOptions<>), typeof(OptionsManager<>), new InjectionSingletonLifetimeManager()) //i am missing ILifetimeContainer argument
```

**Comment by pksorensen** [comment]
This is what i have done for now to make it work. I dont know if this is stupid :(

```
 internal class MyOptionsExtension : UnityContainerExtension
        {
            protected override void Initialize()
            {
               
            }

            public ILifetimeContainer Lifetime => Context.Lifetime;
        }

        [TestMethod]
        public void Test3()
        {
            var container = new UnityContainer().AddExtension(new MyOptionsExtension());

            var lifetime=container.Configure< MyOptionsExtension>().Lifetime;
          
            container.RegisterType<Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest1, Test1>(new HierarchicalLifetimeManager());
            container.RegisterType<ITest2, Test1>(new HierarchicalLifetimeManager());


            container.RegisterType(typeof(IOptions<>), typeof(OptionsManager<>), new InjectionSingletonLifetimeManager(lifetime))
              .RegisterType(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>), new HierarchicalLifetimeManager())
         .RegisterType(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>), new InjectionSingletonLifetimeManager(lifetime))
          .RegisterType(typeof(IOptionsFactory<>), typeof(OptionsFactory<>), new TransientLifetimeManager())
         .RegisterType(typeof(IOptionsMonitorCache<>), typeof(OptionsCache<>), new InjectionSingletonLifetimeManager(lifetime));

            {
                var child = container.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest2>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());

                child.Dispose();
            }
            {
                var child = container.CreateChildContainer();

                var a = child.Resolve<ITest1>();
                var b = child.Resolve<ITest2>();

                Assert.AreEqual(a.GetHashCode(), b.GetHashCode());
            }
             
        }
```

**Comment by ENikS** [comment]
Did you try to add it to ServiceCollection you are passing in?

**Comment by pksorensen** [comment]
The reason is that I use it outside aspnet core context (in service fabric) where some services are not involved with aspnet core and their ServiceCollection. (Aspnet core dont support child containers, thats why i use Unity). 

So the container that goes into aspnet core is actually just a child contianer of my root container .

But we can close this - the solution i found looks to be working for now
